### ISSUE TITLE
IMPORTANT - Open for Transference

### ISSUE THREAD

**Issue by deinok** [graphql-dotnet/graphql-client#147]
I'm sorry but due my work im not able to give the enough time to this library.
So in the following days I will transfer the ownership of all the things related to this library.
So, anybody interested in having the ownership please say it in a comment in this issue.

My recomendations:
The biggest issue that this library has serialize the responses properly. (Due been GraphQL so dynamic, seems pretty much designed with JS in mind)(It can't be properly modelized in C#).
Making something like `graphQLClient.SendQuery<Schema>(request)` should fix most of the problems regarding Blazor and Unity, and making the library more safe and easy to develop.

Again, sorry for not been able to mantain this.

**Comment by sungam3r** [comment]
I can help. I spent quite a lot of time studying this code and supplementing it for myself. I am currently support server-side/core projects - parser, graphq-dotnet, server, examples.

**Comment by rose-a** [comment]
I'd too be willing to support this library, since I'm actively using the beta subscription API...

**Comment by dojo90** [comment]
Since I, like @rose-a , use the current beta release, I am very interested in continuing and advancing the project!

**Comment by deinok** [comment]
My preference is @rose-a , he made a really good job with subscription API, but i was unable to properly review it due things not related to his job with the subscription like:
* A proper HTTP spec don't exists
* General rework for supporting WebGL and less use of `dynamic`

So, @rose-a are you agree with the transfership to you? 
Anybody has inconvenience with this decision?

**Comment by sungam3r** [comment]
It suits me. Anyway, I will help.

**Comment by sidhants** [comment]
It would be great if this repo can be taken forward keeping in mind webGL/Unity/etc. with flexibility to turn off dynamics for requests/responses. I branched out for Unity compatibility and compiled with https://github.com/jilleJr/Newtonsoft.Json-for-Unity for things to work as expected but I am missing out on newer features since this will become a pain to maintain. https://github.com/sidhants/graphql-client/tree/unity-stable-v2.0.0-alpha.2

Really pleased with the initiatives from @rose-a and @sungam3r to keep this project alive. :)

@deinok Something that would be really useful would be a C# generator for graphQL requests so that a common metafile can be used between server and client. Are you aware of anything like this in the plans?

**Comment by sungam3r** [comment]
> Something that would be really useful would be a C# generator for graphQL requests so that a common metafile can be used between server and client. Are you aware of anything like this in the plans?

@sidhants I have one and my team actively uses it in prod. We have dozens of microservices for which CSharp clients are automatically generated. The work on generators is in progress and tracked in graphql-dotnet/graphql-dotnet#1424. While I am delayed by the lack of free time, it remains to open source the CSharp generator. If we talk about the functionality, then the main missing features are custom scalars and subscriptions.

**Comment by deinok** [comment]
@sidhants 
* For fixing the Unity / WebGL bug i recomend moving to System.Text.JSON and forcing the use of <Schema> like methods.
* For Schema generated I had a parsing prototype that was able to create code via a MSBuild Task / That could be released so you guys can use it
* Also, I know that graphQL can be used via IQueryables (like EntityFramework like) as I have developed it. I can't share it as its private from my enterprise. But I can give some advises agains that path
* We also have a GraphQL implementation directly via TCP / SSL via the IGraphQLClient interface. It also implements subscriptions / Can't be shared / The spec can be made public (TCP packages format)

**Comment by OneCyrus** [comment]
we used to use the graphql-client as well. but the dynamic return values make this client really hard to use. now we migrated over to the strawberry shake graphql client.  this has some pretty neat features.

especially full support for type safety. it bascially auto-generates all the C# models from graphql queries (like graphql-code-gen for those of you in the JS world). this helped us a lot to keep our client applications up to date against the graphql server. basically we are using it now as a process in CI to validate our client's usage of the graphql API. and it supports subscriptions too.

you should check it out https://chillicream.com/blog/2019/11/25/strawberry-shake_2

**Comment by sidhants** [comment]
> @sidhants I have one and my team actively uses it in prod. We have dozens of GraphQL microservices for which CSharp clients are automatically generated. The work on generators is in progress and tracked in [graphql-dotnet/graphql-dotnet#1424](https://github.com/graphql-dotnet/graphql-dotnet/issues/1424). While I am delayed by the lack of free time, it remains to open source the CSharp generator. If we talk about the functionality, then the main missing features are custom scalars and subscriptions.

@sungam3r  That would be an awesome tool. Do you have permission from your employer to make it as open source yet?

**Comment by sidhants** [comment]
> @sidhants
> 
> * For fixing the Unity / WebGL bug i recomend moving to System.Text.JSON and forcing the use of  like methods.
> * For Schema generated I had a parsing prototype that was able to create code via a MSBuild Task / That could be released so you guys can use it
> * Also, I know that graphQL can be used via IQueryables (like EntityFramework like) as I have developed it. I can't share it as its private from my enterprise. But I can give some advises agains that path
> * We also have a GraphQL implementation directly via TCP / SSL via the IGraphQLClient interface. It also implements subscriptions / Can't be shared / The spec can be made public (TCP packages format)

@deinok I remember trying System.Text.Json but that had some issues with Unity (dont remember exactly but il2cpp was painful). Unity has its own json library thats why I went ahead and just returned the response to deserialize everything in a Unity wrapper.
- It would be great if you can share the parsing prototype for the schema as it is something that will be very useful rather than hardcoding all the requests.

**Comment by sidhants** [comment]
> we used to use the graphql-client as well. but the dynamic return values make this client really hard to use. now we migrated over to the strawberry shake graphql client. this has some pretty neat features.
> 
> especially full support for type safety. it bascially auto-generates all the C# models from graphql queries (like graphql-code-gen for those of you in the JS world). this helped us a lot to keep our client applications up to date against the graphql server. basically we are using it now as a process in CI to validate our client's usage of the graphql API. and it supports subscriptions too.
> 
> you should check it out https://chillicream.com/blog/2019/11/25/strawberry-shake_2

@OneCyrus Thanks for sharing this. I am going to look into it- especially the auto generation feature!

**Comment by sungam3r** [comment]
@sidhants I have all permissions. The only blocker is free time.

**Comment by rose-a** [comment]
@deinok Ok, let's do this. I don't have too much of free time left over myself (I guess that's a widely spread problem), but I hope I can live up to peoples expectations and bring this library forward.
I'll send you an e-mail to the address given in your profile so you have my contact...

My priorities would be set as follows:

1. Konsolidate the current state and release a version 2.0.0 (including the new subscriptions API)
2. Engage the deserialization "problem". Up to now the current solution did not bother my that much although it certainly is a rich source of bugs (which is therefore thorougly covered with unit tests in all our projects). So I'm quite open to ideas/pull requests on this topic. I'm usually not too thrilled by code generators, but I don't know if there actually is a better solution.

I hope everyone is ok with this...

**Comment by sidhants** [comment]
> @deinok Ok, let's do this. I don't have too much of free time left over myself (I guess that's a widely spread problem), but I hope I can live up to peoples expectations and bring this library forward.
> I'll send you an e-mail to the address given in your profile so you have my contact...
> 
> My priorities would be set as follows:
> 
> 1. Konsolidate the current state and release a version 2.0.0 (including the new subscriptions API)
> 2. Engage the deserialization "problem". Up to now the current solution did not bother my that much although it certainly is a rich source of bugs (which is therefore thorougly covered with unit tests in all our projects). So I'm quite open to ideas/pull requests on this topic. I'm usually not too thrilled by code generators, but I don't know if there actually is a better solution.
> 
> I hope everyone is ok with this...

@rose-a Those are excellent issues to tackle IMO and get this repo back up and running. Really looking forward to the subscriptions api 👍 Appreciate your effort on this.

My two cents for the de-serialization problem since I was fighting this when I initially integrated with Unity. I ended up adding an API which does the job but is kind of "hacky" [https://github.com/sidhants/graphql-client/blob/unity-stable-v2.0.0-alpha.2/src/GraphQL.Client/Http/Internal/GraphQLHttpHandler.cs]

`public async Task<(HttpStatusCode, string)> PostAsyncHttp(GraphQLRequest request, CancellationToken cancellationToken = default)`


My suggestions therefore based on the problems I faced: 
-Since using dynamics is what causes the exceptions on certain platforms, simply providing options to turn dynamics off as part of the initial settings (as @sungam3r had suggested for NewtonSoft https://github.com/graphql-dotnet/graphql-client/issues/133#issuecomment-551036777).
-Providing a flexible API to get raw query responses/errors to the consumer. This way the consumer can do the de-serialization on their end if needed. I use C# Models when de-serializing (hoping to replace that through automatic C# generated code).

I will be willing to help out as well. I am sure there will be great suggestions from others. 
Thanks,
Sidhant

**Comment by deinok** [comment]
Probably we need a roadmap about how to properly fix everything and give some kind of priorities to tasks

**Comment by sidhants** [comment]
> @sidhants I have all permissions. The only blocker is free time.

@sungam3r Any way you can share a version of the generator that I can try on a schema file?

**Comment by sungam3r** [comment]
Theoretically, this is possible, but I will not do it yet, as the code and documentation contain references to my employer. Similarly with the meta-information of the package itself. For legal reasons, I must remove all this information. It takes time to put this in order. This weekend I will have the opportunity to continue working on the generator. There are chances to get something. There are quite a lot of code that needs to be adapted.

**Comment by sidhants** [comment]
> Theoretically, this is possible, but I will not do it yet, as the code and documentation contain references to my employer. Similarly with the meta-information of the package itself. For legal reasons, I must remove all this information. It takes time to put this in order. This weekend I will have the opportunity to continue working on the generator. There are chances to get something. There are quite a lot of code that needs to be adapted.

@sungam3r Totally understand that. Whenever it is in good shape to share! Thanks a lot.

**Comment by chelliwell** [comment]
I realise IP etc is not straight-forward, but I find such comments disappointing given: 
https://github.com/graphql-dotnet/graphql-client/blob/master/LICENSE.txt
....

**Comment by benmccallum** [comment]
Not sure if it's 100% relevant, but thought I'd shared. We use quicktype to generate strongly-typed queries. I wrote a PS script to generate them for each .graphql in our project. And then we have a little TypedGraphQLClient wrapper that has an `ExecuteAsync<TResult>` method, where `TResult` is the type generated by quicktype and the script.

It's not the *nicest* thing in the world, but didn't require us to re-invent any wheels at least.
https://gist.github.com/benmccallum/df9dbf60a205c5be5a1b116cd98d725b

**Comment by sidhants** [comment]
> Not sure if it's 100% relevant, but thought I'd shared. We use quicktype to generate strongly-typed response types from queries in .graphql files. I wrote a PS script to run quicktype across each .graphql in our project. Then we have a little TypedGraphQLClient wrapper that has an `ExecuteAsync<TResult>` method, where `TResult` is the type generated by quicktype.
> 
> It's not the _nicest_ thing in the world, but didn't require us to re-invent any wheels at least.
> https://gist.github.com/benmccallum/df9dbf60a205c5be5a1b116cd98d725b

@benmccallum  This might be useful. Will check it out. Thanks for sharing. I'm also looking at https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin

**Comment by PascalSenn** [comment]
Hi @sidhants , @benmccallum

I see you are still searching for a code generation graphql client. 
I think Strawberry Shake is exactly what you are looking for.
@OneCyrus  mentioned it before.

It is a graphql client that generates c# types for your queries, mutation or subscriptions.
It comes with tooling so that you really only have to set it up once and then the client is generated on every build.
You just have to do this:
1) add reference to StrawberryShake in project file
     currently the newest version is 11.0.0-preview.84
2) install the tool in the project folder
   ` dotnet tool install strawberryshake.tools --version 11.0.0-preview.84`
3) initialize the project
`dotnet graphql init <<graphqlendpoint>> -p <<path fot the client>> -n <<name of the client>>`
e.g.
` dotnet graphql init  http://localhost:60004/graphql -p ./Clients/MyClient -n MyClient`
4) add a query file `Queries.graphql` to the folder /Clients/MyClient
5) register generated client and http client in di
6) build and enjoy. 

more info you find in the blog post, the github repo or on slack

**Comment by benmccallum** [comment]
THanks @PascalSenn, will definitely give it a look. Seems much nicer than our solution.

**Comment by rose-a** [comment]
Downside is that this only works when your server is running and reachable during build, which does not apply to the projects I'm working on (server and client are part of the same solution).

**Comment by benmccallum** [comment]
Yea this is a nightmare for graph projects. Our FE team uses Relay and the compiler. Keeping generated things in sync and having a hosted version for them somewhere that gives them what they need across branches, etc. #funtimes.

**Comment by PascalSenn** [comment]
@rose-a  
The tooling downloads the schema file so. The client is actually generated from this downloaded file. 
You only need to have the server running when you update the schema file.

**Comment by OneCyrus** [comment]
you can also just copy the updated schema file to the directory. no need for a running server once you have set up your client.

**Comment by PascalSenn** [comment]
@benmccallum @maraisr  It is indeed. The solution for it is a schema registry. A plugnplay serivce that manages schemas, schema version, queries and a will have a whole bunch of other features. 
Ping me on twitter if you like to more info
