### ISSUE TITLE
Examples not up to date

### ISSUE THREAD

**Issue by AndyEdmonds** [graphql-dotnet/graphql-client#249]
graphql-client/examples/GraphQL.Client.Example/Program.cs uses GraphQLRequest
Superceded by GraphQLHttPRequest

**Comment by rose-a** [comment]
Using `GraphQLRequest` is perfectly fine and the recommended way to use this library, since it's meant to be transport-agnostic like the GraphQL spec is.

`GraphQLHttpRequest` or a class inheriting from it should only be used if you need to alter the way the request is transformed into a `HttpRequestMessage` (see #216 for an example).

**Comment by AndyEdmonds** [comment]
Hi Alexander.
I used the most recent NuGet package and found that GraphQLRequest was not available/accessible etc. I.e. the compiler couldn't find it. I can't find it in the source either. GraphQLHttpRequest was available. So I assumed you had yet another breaking change and renamed the method. Either way there is something wrong.

**Comment by rose-a** [comment]
The [GraphQLRequest](https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Primitives/GraphQLRequest.cs) class resides within the *GraphQL.Primitives* nuget package, which is a indirect dependency of *GraphQL.Client*.

**Comment by AndyEdmonds** [comment]
There's nothing about this in the readme. In previous versions of this code you used a totally different secondary common library.  Can you see that as a casual user of this code it is confusing not to be told what you need to make use of it?

**Comment by dariusjs** [comment]
I've also had trouble following the examples when specifically trying to implement AWS_IAM authorisation using AWS Appsync. The API key auth as well as OIDC is straight forward and I've gotten those to work.

Is declaring the client as below also deprecated? 

I've found this gist from NeilBorstrom which I am trying to adapt. I think GraphQLClient is now replaced by GraphQLHttpClient 

https://gist.github.com/NeilBostrom/cab8b9275e39bb90ecf8e06ab980664b
```
var graphQLClient = new GraphQLClient("https://example.appsync-api.eu-west-1.amazonaws.com/graphql",
                                        new GraphQLClientOptions
                                        {
                                            HttpMessageHandler = new AWS4SignerMessageHandler(
                                                new AmazonAppSyncClient(),
                                                "--awsAccessKeyId--",
                                                "--awsSecretAccessKey--")
                                        });

```


I'm happy to contribute something to the examples when I get things working. This below is straight forward when using the amazon appsync api keys
```
var graphQLClient = new GraphQLHttpClient(apiendpoint, new NewtonsoftJsonSerializer());
graphQLClient.HttpClient.DefaultRequestHeaders.Add("x-api-key", apikey);
var serialised = await Query.getAllObjects(graphQLClient);
```

**Comment by rose-a** [comment]
@AndyEdmonds You don't need to explicitly add *GraphQL.Primitives* as a dependency, as it is automatically brought in by *GraphQL.Client*.

The example is a valid short example and it compiles and works fine (at least on the workstations I use, feel free to clone the repo and try for yourself).

I've never experienced the problem you described above (the compiler not finding `GraphQLRequest`) in any of my projects. I've experienced symptoms like this on the occasional Visual Studio hickup, which is mostly resolved by restarting VS.

If you can find and share the root cause for your compiler not beeing able to find `GraphQLRequest`, maybe I can reproduce your issue and fix it. But as stated above, the example is the correct and intended way to use this library.

@dariusjs `GraphQLClient` does not exist anymore since v2.0. You have to use `GraphQLHttpClient` if you want to connect to a GraphQL API which is exposed on a HTTP(S) endpoint, which is the most common scenario.

Using tokens with this library is no different from using them with a bare `HttpClient`.

**Comment by john-trieu-nguyen** [comment]
> I've also had trouble following the examples when specifically trying to implement AWS_IAM authorisation using AWS Appsync. The API key auth as well as OIDC is straight forward and I've gotten those to work.

@dariusjs I'm looking to do something similar. Have you got it working on your end?

**Comment by dariusjs** [comment]
> > I've also had trouble following the examples when specifically trying to implement AWS_IAM authorisation using AWS Appsync. The API key auth as well as OIDC is straight forward and I've gotten those to work.
> 
> @dariusjs I'm looking to do something similar. Have you got it working on your end?

I ended up implementing it with the standard http library as well as awsv4 signatures. I didn’t spend too much time on the websocket connectivity. I can post a snippet at the end of the weekend.
