### ISSUE TITLE
Connecting websocket to apollo server

### ISSUE THREAD

**Issue by andylhansen** [graphql-dotnet/graphql-client#250]
I am trying to create a subscription to my apollo server running on node.js.

I am getting the error: "binary websocket messages are not supported" which I see is in the GraphQLHttpWebSocket class.

Does anyone have any experience using graphql-client to connect a websocket to an apollo server, or what configuration would be needed to make it connect correctly?

**Comment by rose-a** [comment]
It seems your server responds with a binary stream to the GraphQL request. I suspect that happens when the server compresses the websocket payload.

Does your server try to compress the message (*permessage-deflate* websocket extension)? This is currently not supported by .NET Core, but propably will be available in .NET 5 (see [the corresponding issue](https://github.com/dotnet/runtime/issues/20004)).

Please confirm if compression was causing this...

**Comment by andy-reach** [comment]
Apollo server doesn't have a setting to configure that. I've inquired in the apollo-server repo for additional information.

**Comment by rose-a** [comment]
https://github.com/apollographql/apollo-server/issues/2791

**Comment by rose-a** [comment]
@didimitrie discovered the underlying cause, work is tracked in #272
