### ISSUE TITLE
Doubts about HTTP exception processing

### ISSUE THREAD

**Issue by SapphireBrand** [graphql-dotnet/graphql-client#26]
The code for ReadHttpResponseMessageAsync only checks for a valid HTTP status code if the Json parsing throws an exception. Is that strictly correct? That is, is it guaranteed that every HTTP error returned by the server will result in a Json parse exception?

My code always looks like this:

```c#
using (var response = await httpClient.PostAsync("shredding-results", request, mediaTypeFormatter).ConfigureAwait(false))
{
    response.EnsureSuccessStatusCode();
    return await response.Content.ReadAsAsync<ShreddingResult>().ConfigureAwait(false);
}
```

**Comment by deinok** [comment]
Well, a GraphQL server have 3 types of responses:
* Valid GraphQL Response - Valid HttpCode (Expected behaviour)
* Valid GraphQL Response - Invalid HttpCode (Error is in the GraphQLResponse object)
* Invalid GraphQL Response - Invalid HttpCode (Not a GraphQL error but should be controlled)

The ReadHttpResponseMessageAsync controlls the three scenarios by:
* Reading the Body and try to parse it as a valid GraphQLResponse
* If valid, return GraphQLResponse
* If invalid and invalid HttpCode -> GraphQLException
* Else, a true JsonParsing exception

So, I think that the code follows the expected behaviour in non edge scenarios

**Comment by SapphireBrand** [comment]
There is no need (or benefit) from assuming that the system you are talking to is a GraphQL server. I'm serious. It's just a web server on the internet.

The safer code here is also less tricky, with less need for analysis, and fewer dependencies.

**Comment by SapphireBrand** [comment]
OK, I see your point. We have to parse the response to get the Errors field, so we have to start by assuming that there is a valid GraphQL response, then deal with other possibilities when we see that something went wrong.

So I would close the issue.

**Comment by deinok** [comment]
@SapphireBrand Even with this, I think that the usage of `ReadAsAsync<ShreddingResult>()` should work pretty well, except for the cases when a `Encoding: gzip` is enabled (to explore if the method decompress it)
ref: #23 
So for now I will let this open until I explore the gzip decompresion
