### ISSUE TITLE
ErrorPath is failing while serialization the Json response

### ISSUE THREAD

**Issue by hemanthpolani** [graphql-dotnet/graphql-client#263]
I am using your GraphQL.Client 3.1.3. it was working great still last two weeks but when my service provider added a path string in error list. it started breaking in our client side code.

Error in Json serialization:

**One or more errors occurred. (Error converting value "string" to type 'GraphQL.ErrorPath'. Path 'errors[0].path', line 1, position 181.)**

Response:

```json
{
 "errors": [
        {
            "code": "****",
            "message": "****",
            "developerMessage": "*****",
            "path": "*****",
            "moreInfo": "***",
            "timeStamp": 1597693810711
        }
    ],
    "data": {}
}
```

Code structure:

```csharp
public class ClientError
    {
        [JsonProperty("code")]
        public string Code { get; set; }
        [JsonProperty("message")]
        public string Message { get; set; }
        [JsonProperty("developerMessage")]
        public string DeveloperMessage { get; set; }
        [JsonProperty("moreInfo")]
        public string MoreInfo { get; set; }
        [JsonProperty("timeStamp")]
        public long TimeStamp { get; set; }
        [JsonProperty("path")]
        public string Path{ get; set; }
    }
```

Kindly help me resolve this.

Appreciate your help.

**Comment by rose-a** [comment]
The response content from your e-mail:

```json
{
    "errors": [{
        "code": "NO_GROUP_BILLING",
        "message": "No billing details found for the group",
        "developerMessage": "No billing details found for the group",
        "path": "getLargeGroupClientInfo",
        "moreInfo": "https://xxxxxxxxxxxxx.com/docs/common-errors",
        "timeStamp": 1597693810711
    }],
    "data": {}
}
```

The error format is specified in https://spec.graphql.org/June2018/#sec-Errors. The reason why `path` fails to deserialize is because `path` *should be a list of path segments starting at the root of the response and ending with the field associated with the error*.

You also won't be able to deserialize the fields `developerMessage`, `moreInfo` and `timestamp`, since those don't exist on [GraphQLError](https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Primitives/GraphQLError.cs) and which according to the spec should go into the `extensions` map.

Is there any chance you can "persuade" your provider to follow the GraphQL spec on this?

I suspect you're using *System.Text.Json* for serialization?
