### ISSUE TITLE
How to deserialize response to object?

### ISSUE THREAD

**Issue by Oleg26Dev** [graphql-dotnet/graphql-client#347]
How to convert the GraphQL response to object on the client?
I do this way:
```
                var request = new GraphQLRequest
                {
                    Query = @"{customer(id:4){id,firstName,lastName,contact,email}}"
                };
                var jsonSerializer = new njs.NewtonsoftJsonSerializer();
                using var graphQLClient = new GraphQLHttpClient("https://localhost:5011/graphql/", jsonSerializer);
                //var response = await graphQLClient.SendQueryAsync<Customer>(request);
                var response = await graphQLClient.SendQueryAsync<dynamic>(request);
                var graphQLQueryType = @"customer";
                var cust = response;//.Data..customer;

                var stringResult = response.Data.ToString();
                var resultzzz = JsonConvert.DeserializeObject<List<Customer>>(stringResult);
```

and the result as a string is:
stringResult = "{\r\n  \"customer\": {\r\n    \"id\": \"4\",\r\n    \"firstName\": \"Name#4\",\r\n    \"lastName\": \"LastName#4\",\r\n    \"contact\": \"Contact#4\",\r\n    \"email\": \"you#4@mai.com\"\r\n  }\r\n}"

It is ok.
But I need to deserialize this response to object class Customer.

and this 
 var resultzzz = JsonConvert.DeserializeObject<List<Customer>>(stringResult);
gives me:
`ex = {"Cannot deserialize the current JSON object (e.g. {\"name\":\"value\"}) into type 'System.Collections.Generic.List`1[GraphQL.Client.Example.Customer]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.\r\nTo fix this error eith...
`

What I do wrong? How to fix it?

**Comment by frjonsen** [comment]
I see this issue is resolved, but with no solution. I'm currently having the same issue. What was your solution?

**Comment by rose-a** [comment]
The OP tried to deserialize a JSON object into a field of type `List<Customer>` (thats what the exception says...)

**Comment by frjonsen** [comment]
I actually only a couple minutes ago realized that my issue was something similar.

I was expecting to get a data structure in the shape of `EventData: [ EventDataItems ]`, but I was actually getting `EventData: { items: [ EventDataItems] }`

Running `var res = await client.SendQueryAsync(request, () => new { EventData = new List<EventData>() });` then obviously failed.

The error I was getting was also `Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Queue.Library.Models.EventData]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.`.

The thing here was that I misinterpreted the error message. I interpreted "the type" as referring to "the current JSON object" in the API response, and not as referring to the List I was trying to convert it to. Perhaps this was more a failure of my skill with the English language than anything technical.
