### ISSUE TITLE
how to use GraphQLWebSocketRequest?

### ISSUE THREAD

**Issue by Shadow4walker** [graphql-dotnet/graphql-client#386]
I've searched around and there's no way to accespt "GraphQLWebSocketRequest" class as a request! i need to send WebSocket Request to the wss AWS AppSync so i need to set "id,Payload,Type" within sent request json
but those proprites are only available in the GraphQLWebSocketRequest and idk what's the use of this class since i can't use it anyware!
we need more complex samples since the example in this repo is very basic!

**Comment by rose-a** [comment]
`GraphQLWebSocketRequest` is not meant to be used directly. Configure your `GraphQLHttpClient` to use websockets for queries and mutations (if that's what you're after). Subscriptions always use websockets (because they only work this way).
Then use a regular `GraphQlRequest`.

I'm personally not familiar with AWS AppSync, but there are lots of discussions and working examples in the issues. (i.e. here: https://github.com/graphql-dotnet/graphql-client/issues/377).

I'll happily accept a PR with a working AppSync example (or as suggested in the above issue, a APPSync-specific extension)
